services:
  server:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    network_mode: host
    restart: always
